/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package tr.com.rcesur.kafka.avromodels;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Address extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8533302190841713199L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Address\",\"namespace\":\"tr.com.rcesur.kafka.avromodels\",\"fields\":[{\"name\":\"zip\",\"type\":\"string\",\"doc\":\"the zip of a address\"},{\"name\":\"city\",\"type\":\"string\",\"doc\":\"the city of a address\"},{\"name\":\"street\",\"type\":\"string\",\"doc\":\"the street of a address\"},{\"name\":\"streetNumber\",\"type\":\"string\",\"doc\":\"the street number of a address\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Address> ENCODER =
      new BinaryMessageEncoder<Address>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Address> DECODER =
      new BinaryMessageDecoder<Address>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Address> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Address> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Address>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Address to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Address from a ByteBuffer. */
  public static Address fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** the zip of a address */
  @Deprecated public java.lang.CharSequence zip;
  /** the city of a address */
  @Deprecated public java.lang.CharSequence city;
  /** the street of a address */
  @Deprecated public java.lang.CharSequence street;
  /** the street number of a address */
  @Deprecated public java.lang.CharSequence streetNumber;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Address() {}

  /**
   * All-args constructor.
   * @param zip the zip of a address
   * @param city the city of a address
   * @param street the street of a address
   * @param streetNumber the street number of a address
   */
  public Address(java.lang.CharSequence zip, java.lang.CharSequence city, java.lang.CharSequence street, java.lang.CharSequence streetNumber) {
    this.zip = zip;
    this.city = city;
    this.street = street;
    this.streetNumber = streetNumber;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return zip;
    case 1: return city;
    case 2: return street;
    case 3: return streetNumber;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: zip = (java.lang.CharSequence)value$; break;
    case 1: city = (java.lang.CharSequence)value$; break;
    case 2: street = (java.lang.CharSequence)value$; break;
    case 3: streetNumber = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'zip' field.
   * @return the zip of a address
   */
  public java.lang.CharSequence getZip() {
    return zip;
  }

  /**
   * Sets the value of the 'zip' field.
   * the zip of a address
   * @param value the value to set.
   */
  public void setZip(java.lang.CharSequence value) {
    this.zip = value;
  }

  /**
   * Gets the value of the 'city' field.
   * @return the city of a address
   */
  public java.lang.CharSequence getCity() {
    return city;
  }

  /**
   * Sets the value of the 'city' field.
   * the city of a address
   * @param value the value to set.
   */
  public void setCity(java.lang.CharSequence value) {
    this.city = value;
  }

  /**
   * Gets the value of the 'street' field.
   * @return the street of a address
   */
  public java.lang.CharSequence getStreet() {
    return street;
  }

  /**
   * Sets the value of the 'street' field.
   * the street of a address
   * @param value the value to set.
   */
  public void setStreet(java.lang.CharSequence value) {
    this.street = value;
  }

  /**
   * Gets the value of the 'streetNumber' field.
   * @return the street number of a address
   */
  public java.lang.CharSequence getStreetNumber() {
    return streetNumber;
  }

  /**
   * Sets the value of the 'streetNumber' field.
   * the street number of a address
   * @param value the value to set.
   */
  public void setStreetNumber(java.lang.CharSequence value) {
    this.streetNumber = value;
  }

  /**
   * Creates a new Address RecordBuilder.
   * @return A new Address RecordBuilder
   */
  public static tr.com.rcesur.kafka.avromodels.Address.Builder newBuilder() {
    return new tr.com.rcesur.kafka.avromodels.Address.Builder();
  }

  /**
   * Creates a new Address RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Address RecordBuilder
   */
  public static tr.com.rcesur.kafka.avromodels.Address.Builder newBuilder(tr.com.rcesur.kafka.avromodels.Address.Builder other) {
    return new tr.com.rcesur.kafka.avromodels.Address.Builder(other);
  }

  /**
   * Creates a new Address RecordBuilder by copying an existing Address instance.
   * @param other The existing instance to copy.
   * @return A new Address RecordBuilder
   */
  public static tr.com.rcesur.kafka.avromodels.Address.Builder newBuilder(tr.com.rcesur.kafka.avromodels.Address other) {
    return new tr.com.rcesur.kafka.avromodels.Address.Builder(other);
  }

  /**
   * RecordBuilder for Address instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Address>
    implements org.apache.avro.data.RecordBuilder<Address> {

    /** the zip of a address */
    private java.lang.CharSequence zip;
    /** the city of a address */
    private java.lang.CharSequence city;
    /** the street of a address */
    private java.lang.CharSequence street;
    /** the street number of a address */
    private java.lang.CharSequence streetNumber;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(tr.com.rcesur.kafka.avromodels.Address.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.zip)) {
        this.zip = data().deepCopy(fields()[0].schema(), other.zip);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.city)) {
        this.city = data().deepCopy(fields()[1].schema(), other.city);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.street)) {
        this.street = data().deepCopy(fields()[2].schema(), other.street);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.streetNumber)) {
        this.streetNumber = data().deepCopy(fields()[3].schema(), other.streetNumber);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Address instance
     * @param other The existing instance to copy.
     */
    private Builder(tr.com.rcesur.kafka.avromodels.Address other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.zip)) {
        this.zip = data().deepCopy(fields()[0].schema(), other.zip);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.city)) {
        this.city = data().deepCopy(fields()[1].schema(), other.city);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.street)) {
        this.street = data().deepCopy(fields()[2].schema(), other.street);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.streetNumber)) {
        this.streetNumber = data().deepCopy(fields()[3].schema(), other.streetNumber);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'zip' field.
      * the zip of a address
      * @return The value.
      */
    public java.lang.CharSequence getZip() {
      return zip;
    }

    /**
      * Sets the value of the 'zip' field.
      * the zip of a address
      * @param value The value of 'zip'.
      * @return This builder.
      */
    public tr.com.rcesur.kafka.avromodels.Address.Builder setZip(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.zip = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'zip' field has been set.
      * the zip of a address
      * @return True if the 'zip' field has been set, false otherwise.
      */
    public boolean hasZip() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'zip' field.
      * the zip of a address
      * @return This builder.
      */
    public tr.com.rcesur.kafka.avromodels.Address.Builder clearZip() {
      zip = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'city' field.
      * the city of a address
      * @return The value.
      */
    public java.lang.CharSequence getCity() {
      return city;
    }

    /**
      * Sets the value of the 'city' field.
      * the city of a address
      * @param value The value of 'city'.
      * @return This builder.
      */
    public tr.com.rcesur.kafka.avromodels.Address.Builder setCity(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.city = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'city' field has been set.
      * the city of a address
      * @return True if the 'city' field has been set, false otherwise.
      */
    public boolean hasCity() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'city' field.
      * the city of a address
      * @return This builder.
      */
    public tr.com.rcesur.kafka.avromodels.Address.Builder clearCity() {
      city = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'street' field.
      * the street of a address
      * @return The value.
      */
    public java.lang.CharSequence getStreet() {
      return street;
    }

    /**
      * Sets the value of the 'street' field.
      * the street of a address
      * @param value The value of 'street'.
      * @return This builder.
      */
    public tr.com.rcesur.kafka.avromodels.Address.Builder setStreet(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.street = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'street' field has been set.
      * the street of a address
      * @return True if the 'street' field has been set, false otherwise.
      */
    public boolean hasStreet() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'street' field.
      * the street of a address
      * @return This builder.
      */
    public tr.com.rcesur.kafka.avromodels.Address.Builder clearStreet() {
      street = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'streetNumber' field.
      * the street number of a address
      * @return The value.
      */
    public java.lang.CharSequence getStreetNumber() {
      return streetNumber;
    }

    /**
      * Sets the value of the 'streetNumber' field.
      * the street number of a address
      * @param value The value of 'streetNumber'.
      * @return This builder.
      */
    public tr.com.rcesur.kafka.avromodels.Address.Builder setStreetNumber(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.streetNumber = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'streetNumber' field has been set.
      * the street number of a address
      * @return True if the 'streetNumber' field has been set, false otherwise.
      */
    public boolean hasStreetNumber() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'streetNumber' field.
      * the street number of a address
      * @return This builder.
      */
    public tr.com.rcesur.kafka.avromodels.Address.Builder clearStreetNumber() {
      streetNumber = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Address build() {
      try {
        Address record = new Address();
        record.zip = fieldSetFlags()[0] ? this.zip : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.city = fieldSetFlags()[1] ? this.city : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.street = fieldSetFlags()[2] ? this.street : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.streetNumber = fieldSetFlags()[3] ? this.streetNumber : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Address>
    WRITER$ = (org.apache.avro.io.DatumWriter<Address>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Address>
    READER$ = (org.apache.avro.io.DatumReader<Address>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
